### ISSUE TITLE
Install script requires `unzip` but doesn't check/install it

### ISSUE THREAD

**Issue by neil-greenwood** [fossas/spectrometer#269]
```
[root@7a6cfdaa4efe al-sysmon]# curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/spectrometer/master/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9462  100  9462    0     0  12713      0 --:--:-- --:--:-- --:--:-- 12717
fossas/spectrometer info checking GitHub for latest tag
fossas/spectrometer info found version: 2.9.0 for v2.9.0/linux/amd64
bash: line 49: unzip: command not found
```

**Comment by scruffystuffs** [comment]
We're probably not going to fix this, for a few reasons:

- We don't want to attempt to install any software on user's environments, other than the `fossa` tool itself.
- When attempting to run pre-existing tools, it's usually better to ask for forgiveness instead of permission.
- We are going to refactor the install script soon, and we may not need to zip/unzip at all.
- There is a very easy workaround here: install `unzip` on your system.

Thank you for bringing this to our attention, but at the moment, we can definitively say that we won't fix this.
